### ISSUE TITLE
jsonload does not read unicode characters properly

### ISSUE THREAD

**Issue by sertansenturk** [fangq/jsonlab#3]
Hi, 

I have a fork of this repository, where I have made some simple tweaks. Yesterday, I've realized that when I tried to read json files with Unicode characters, jsonload was disrupting the characters. It is a problem of fopen/fread and made a quick fix: sertansenturk/jsonlab@0fcbb7703e30d3e0db2033a3fc39f23990457eb7

I thought you would be interested to check this and incorporate if there are no problems with this way of reading. 

I am not sure if it's the best way to handle it, but things seem to work properly. I'm welcome to any criticism.

**Comment by fangq** [comment]
@sertansenturk 

thanks for the patch. because fileread does not exist in octave 3.2 or earlier, so I made the following change

https://github.com/fangq/jsonlab/commit/db4e3cadcf732a2bb89a7531e7ddd0ad3a2c67a8

I tested it with matlab/octave 3.2/3.6/3.8 and was able to read a unicode encoded json file.

I am closing this bug, but feel free to open if the problem persists.
