### ISSUE TITLE
Error loading JSON with numbers in the fields

### ISSUE THREAD

**Issue by maurice1979** [fangq/jsonlab#33]
Im trying to load a JSON (test.json) file with dates and numbers in the data structure. This is the content of the JSON file:

> {"status":"OK","statuscode":200,"payload":{"data":{"324163":{"20170317190000":{"dd":187,"var_01":0,"var_02":0,"var_03":0,"var_04":0,"var_05":5,"var_06":5.8,"var_07":62,"e":0,"var_08":8,"var_09":0,"var_10":0,"var_02_max":0},"20170316180000":{"dd":8,"var_01":0,"var_02":0,"var_03":0,"var_04":0,"var_05":4,"var_06":7.8,"var_07":53,"e":0,"var_08":13,"var_09":0,"var_10":0,"var_02_max":0},"20170316234500":{"dd":18,"var_01":0,"var_02":0,"var_03":0,"var_04":0,"var_05":1,"var_06":4.2,"var_07":68,"e":0,"var_08":13,"var_09":0,"var_10":0,"var_02_max":0},"20170316013000":{"dd":14,"var_01":0,"var_02":0,"var_03":0,"var_04":0,"var_05":2,"var_06":3.8,"var_07":77,"e":0,"var_08":10,"var_09":0,"var_10":0,"var_02_max":0},"20170316044500":{"dd":91,"var_01":0,"var_02":1,"var_03":0,"var_04":0,"var_05":4,"var_06":2.1,"var_07":85,"e":0,"var_08":6,"var_09":0,"var_10":0,"var_02_max":2},"20170316184500":{"dd":13,"var_01":0,"var_02":0,"var_03":0,"var_04":0,"var_05":4,"var_06":7.2,"var_07":55,"e":0,"var_08":13,"var_09":0,"var_10":0,"var_02_max":0},"20170316221500":{"dd":16,"var_01":0,"var_02":0,"var_03":0,"var_04":0,"var_05":2,"var_06":5.1,"var_07":64,"e":0,"var_08":13,"var_09":0,"var_10":0,"var_02_max":0}}}}}

After loading the data with Matlab with:

> data = loadjson('test.json');

the ID='' and the dates (in format yyyymmddHHMMSS) from the file appears as follows:

ID = '324163'' (in file)                    --> ID =  'x0x33_24163' (in the object)
date = '20170317190000'  (in file) --> date = 'x0x32_0170317190000' (in the object)

It looks like the function is unable to parse the field named formed by numbers. Is there any workaround to retrieve these numbers just as they appear in the file?

Thanks

**Comment by fangq** [comment]
@maurice1979, loadjson converts a JSON file into a matlab struct. Unfortunately, matlab forbids using all digits as fieldname or variable name. Please see 

http://www.mathworks.com/help/matlab/ref/isvarname.html
http://www.mathworks.com/help/matlab/matlab_prog/variable-names.html
https://www.mathworks.com/help/matlab/ref/genvarname.html

or [this book chapter](https://books.google.com/books?id=6jYDBQAAQBAJ&pg=PT63&lpg=PT63&dq=variable+name+requirement+digits+letters+matlab&source=bl&ots=B5Hus5gQIM&sig=uHrqQA1aMKvCs5Pz3adH87q-yws&hl=en&sa=X&ved=0ahUKEwiMnvCO99jSAhVp4IMKHVk8D5UQ6AEIPjAG#v=onepage&q=variable%20name%20requirement%20digits%20letters%20matlab&f=false).

so, loadjson converts an invalid ID into a valid struct field name so that you can access its value inside matlab. When you save this struct back to a JSON file using savejson, these converted fields are automatically converted back to the original ID string.

For this reason, I marked this issue as "wontfix", and close the issue. If you find other issues related to this, feel free to reopen.
