### ISSUE TITLE
Will jsonlab support datetime de/serialization?

### ISSUE THREAD

**Issue by jdistlr** [fangq/jsonlab#7]
Perhaps I am missing some facts but at the moment it seems there is no way to serialize datetime-types? 

```
>> t = datetime('now')

t = 

   18-Jul-2015 16:03:15

>> foo = struct('poc', t)

foo = 

    poc: [1x1 datetime]

>> json = savejson('', foo)
Error using savejson>mat2json (line 339)
input is not an array

Error in savejson>obj2json (line 163)
    txt=mat2json(name,item,level,varargin{:});

Error in savejson>struct2json (line 268)
	    txt=sprintf('%s%s',txt,obj2json(names{e},item(i,j).(names{e}),...

Error in savejson>obj2json (line 159)
    txt=struct2json(name,item,level,varargin{:});

Error in savejson (line 129)
json=obj2json(rootname,obj,rootlevel,opt);
```

Would be great to see such a feature in future versions.
Thank you for all your efforts in creating this great toolbox!

**Comment by fangq** [comment]
Yes, matlab classes are not currently supported by jsonlab.

https://github.com/fangq/jsonlab/blob/master/README.txt#L364

It is not clear to me how to encode/decode a class object because there are both properties and methods that need to be packed and unpacked to ensure the reproduciblity of the object.

If all you interested is the date-time string, you should consider to use datestr() and datanum() to record the date&time in strings or integers; those are the universal formats suited for general-purpose data exchange.
