### ISSUE TITLE
Msgpack data types

### ISSUE THREAD

**Issue by bthcode** [fangq/jsonlab#74]
Hi there,

First, thank you for the really good library you've put together.  

Seeing different type handling in json vs. msgpack:

JSON:  doubles saved as doubles, loaded as double:

>> x = [1.0,2.0,3.0]; y = savejson(x); z = loadjson(y); q = z.x; whos q
  Name      Size            Bytes  Class     Attributes

  q         1x3                24  double       

MsgPack: doubles saved as doubles, loaded as int8:

x = [1.0,2.0,3.0]; y = savemsgpack(x); z = loadmsgpack(y); whos z

  Name      Size            Bytes  Class    Attributes

  z         3x1                 3  uint8

**Comment by fangq** [comment]
@bthcode, sorry for the delay, only noticed this post today.

regarding your question, the range-dependent type down-casting was intentional. if this change of data type is undesired, you may use the `KeepType` flag to disable it, see

https://github.com/fangq/jsonlab/blob/master/savebj.m#L105-L107

let me know if this flag works for you - if so, feel free to close this ticket. thanks
