### ISSUE TITLE
Slash (/) written as "\/" in the resulting file

### ISSUE THREAD

**Issue by sjeung** [fangq/jsonlab#82]
Hi!
I am using jsonlab in fieldtrip data2bids as described in #71.
After discussion with @robertoostenveld it came up that "n/a" entries are written as "n\\/a" in the resulting .json file. 
I believe the function savejson in line 39 is causing this.
https://github.com/fieldtrip/fieldtrip/blob/e1891eadf1788157dd26ba93b16851078994b281/fileio/ft_write_json.m

I am not really deep into the json related scripts but thought to bring it to your attention.

Cheers, 
Sein

**Comment by fangq** [comment]
@sjeung, `/` can be escaped as `\/` in JSON, which has been listed in the official website/syntax at http://json.org (see [this diagram](https://www.json.org/img/string.png)) and [many other places](https://www.google.com/search?q=json+solidus+escape&oq=json+solidus+escape).

However, some recognized that escaping `/` is [not required](https://mondotondo.com/2010/12/29/the-solidus-issue/) in the specification - although allowed. Because of this, about a month ago, we [disabled this escaping](https://github.com/fangq/jsonlab/commit/2278bb1c387dec39688e7dbd5606fcb9cdd1a8c9) in `savejson` (`loadjson` still parses `\/`). 

Because @robertoostenveld updated JSONLab back in March in [this PR](https://github.com/fieldtrip/fieldtrip/pull/2002), so, it does not contain this change. If stop esccaping `/` is desired, we can ask @robertoostenveld to update the JSONLab with the latest version.

**Comment by sjeung** [comment]
Thanks for the fast reply, yes, I think it will be indeed nice to skip escape in this case. Although it was not problematic to put the resulting data through validator, the [specification](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#:~:text=Throughout%20BIDS%20you%20can%20indicate%20missing%20values%20with%20n/a%20(for%20%22not%20available%22).) states that "not applicable" is to be written as "n/a".

**Comment by fangq** [comment]
@sjeung, it is my opinion that BIDS should allow escaping `n/a` as `n\/a` when written in the JSON sidecar file, because any JSON-compatible parser should unescape `n\/a` back to `n/a` thus they are equivalent.

nonetheless, for the default setting of JSONLab, if the unescaped version is the preference, then updating to the latest code would fix it.

**Comment by robertoostenveld** [comment]
Ok, updating jsonlab is something for me to do.
Thanks for the quick response.

**Comment by sjeung** [comment]
Thank you both, I will close the issue as we found the solution for now.
